import type { PickupGame } from "@/lib/types";

export const fakeGames: PickupGame[] = [
  {
    id: "1",
    title: "Saturday Morning Run",
    locationName: "Lincoln Park Courts",
    area: "North Side, Chicago",
    dateTimeDisplay: "Sat, Jun 14 · 9:00 AM",
    gameType: "5v5",
    currentPlayers: 7,
    maxPlayers: 10,
    competitiveness: "Competitive",
    skillRange: { min: "Intermediate", max: "Advanced" },
    notes: "Full-court games to 11, win stays on. Bring a light and dark shirt.",
  },
  {
    id: "2",
    title: "After-Work Pickup",
    locationName: "Mission Rec Center",
    area: "Mission District, San Francisco",
    dateTimeDisplay: "Tue, Jun 17 · 6:30 PM",
    gameType: "4v4",
    currentPlayers: 5,
    maxPlayers: 8,
    competitiveness: "Casual",
    skillRange: { min: "Beginner", max: "Intermediate" },
    notes: "Relaxed half-court runs. Good for newer players still learning the game.",
  },
  {
    id: "3",
    title: "Elite Hooper Showdown",
    locationName: "Venice Beach Courts",
    area: "Venice, Los Angeles",
    dateTimeDisplay: "Sun, Jun 15 · 4:00 PM",
    gameType: "5v5",
    currentPlayers: 9,
    maxPlayers: 10,
    competitiveness: "Highly Competitive",
    skillRange: { min: "Advanced", max: "Elite" },
    notes: "Ex-college and semi-pro level. Fast pace, real defense, keep score.",
  },
  {
    id: "4",
    title: "Lunchtime 3s",
    locationName: "Downtown YMCA",
    area: "Capitol Hill, Seattle",
    dateTimeDisplay: "Wed, Jun 18 · 12:00 PM",
    gameType: "3v3",
    currentPlayers: 3,
    maxPlayers: 6,
    competitiveness: "Competitive",
    skillRange: { min: "Intermediate", max: "Advanced" },
    notes: "Quick half-court 3v3 games on lunch break. In and out within an hour.",
  },
];
